import '../models/product.dart';

class MockData {
  static List<Product> products = [
    // Fashion
    Product(
      id: '1',
      name: 'Men\'s Casual Cotton Shirt',
      category: 'Fashion',
      price: 1299,
      discountPrice: 699,
      discountPercent: 46,
      rating: 4.2,
      reviewCount: 128,
      imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&q=80',
      description: 'Comfortable and stylish casual shirt made from 100% pure cotton. Perfect for everyday wear.',
      sizes: ['S', 'M', 'L', 'XL'],
    ),
    Product(
      id: '2',
      name: 'Women\'s Floral Summer Dress',
      category: 'Fashion',
      price: 1999,
      discountPrice: 999,
      discountPercent: 50,
      rating: 4.5,
      reviewCount: 342,
      imageUrl: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400&q=80',
      description: 'Beautiful floral printed summer dress, lightweight and breathable.',
      sizes: ['XS', 'S', 'M', 'L'],
    ),
    Product(
      id: '3',
      name: 'Classic Blue Denim Jeans',
      category: 'Fashion',
      price: 2499,
      discountPrice: 1299,
      discountPercent: 48,
      rating: 4.0,
      reviewCount: 89,
      imageUrl: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400&q=80',
      description: 'Premium quality classic blue denim jeans with a comfortable fit.',
      sizes: ['28', '30', '32', '34'],
    ),
    Product(
      id: '4',
      name: 'Formal Leather Oxford Shoes',
      category: 'Fashion',
      price: 3999,
      discountPrice: 1999,
      discountPercent: 50,
      rating: 4.6,
      reviewCount: 56,
      imageUrl: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&q=80',
      description: 'Elegant formal shoes made from genuine leather. Ideal for office and occasions.',
      sizes: ['7', '8', '9', '10', '11'],
    ),
    
    // Electronics
    Product(
      id: '5',
      name: 'Wireless Bluetooth Earbuds',
      category: 'Electronics',
      price: 2999,
      discountPrice: 999,
      discountPercent: 66,
      rating: 3.9,
      reviewCount: 1024,
      imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&q=80',
      description: 'True wireless earbuds with active noise cancellation and 24-hour battery life.',
    ),
    Product(
      id: '6',
      name: 'Smart Fitness Watch',
      category: 'Electronics',
      price: 4999,
      discountPrice: 1499,
      discountPercent: 70,
      rating: 4.3,
      reviewCount: 672,
      imageUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400&q=80',
      description: 'Track your steps, heart rate, and sleep with this advanced fitness smartwatch.',
    ),
    Product(
      id: '7',
      name: '10000mAh Power Bank',
      category: 'Electronics',
      price: 1499,
      discountPrice: 799,
      discountPercent: 46,
      rating: 4.7,
      reviewCount: 312,
      imageUrl: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&q=80',
      description: 'Fast charging power bank with dual USB output ports.',
    ),
    Product(
      id: '8',
      name: 'Over-Ear Wireless Headphones',
      category: 'Electronics',
      price: 5999,
      discountPrice: 2499,
      discountPercent: 58,
      rating: 4.4,
      reviewCount: 220,
      imageUrl: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=400&q=80',
      description: 'High-fidelity audio with deep bass and premium comfort for long listening sessions.',
    ),

    // Beauty
    Product(
      id: '9',
      name: 'Matte Liquid Lipstick',
      category: 'Beauty',
      price: 799,
      discountPrice: 399,
      discountPercent: 50,
      rating: 4.1,
      reviewCount: 450,
      imageUrl: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=400&q=80',
      description: 'Long-lasting matte liquid lipstick that stays on all day without drying your lips.',
      sizes: ['Ruby Red', 'Nude Pink', 'Plum'],
    ),
    Product(
      id: '10',
      name: 'Hydrating Face Serum',
      category: 'Beauty',
      price: 1299,
      discountPrice: 899,
      discountPercent: 30,
      rating: 4.8,
      reviewCount: 189,
      imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&q=80',
      description: 'Boosts skin hydration and glow with Hyaluronic Acid and Vitamin C.',
    ),
    Product(
      id: '11',
      name: 'Eyeshadow Palette',
      category: 'Beauty',
      price: 1499,
      discountPrice: 999,
      discountPercent: 33,
      rating: 4.6,
      reviewCount: 340,
      imageUrl: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=400&q=80',
      description: '18 vibrant shades with a mix of matte and shimmer finishes.',
    ),
    Product(
      id: '12',
      name: 'Organic Aloe Vera Gel',
      category: 'Beauty',
      price: 499,
      discountPrice: 249,
      discountPercent: 50,
      rating: 4.5,
      reviewCount: 920,
      imageUrl: 'https://images.unsplash.com/photo-1629198688000-71f23e745b6e?w=400&q=80',
      description: 'Pure, organic aloe vera gel for soothing skin and scalp.',
    ),

    // Home
    Product(
      id: '13',
      name: 'Aesthetic Table Lamp',
      category: 'Home',
      price: 1999,
      discountPrice: 1199,
      discountPercent: 40,
      rating: 4.2,
      reviewCount: 88,
      imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&q=80',
      description: 'Modern minimalist table lamp perfect for study or bedside.',
    ),
    Product(
      id: '14',
      name: 'Cotton Bedsheet with 2 Pillow Covers',
      category: 'Home',
      price: 1599,
      discountPrice: 899,
      discountPercent: 43,
      rating: 4.3,
      reviewCount: 215,
      imageUrl: 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=400&q=80',
      description: 'Premium soft cotton double bedsheet with beautiful geometric prints.',
      sizes: ['Queen', 'King'],
    ),
    Product(
      id: '15',
      name: 'Ceramic Coffee Mug Set (4 pcs)',
      category: 'Home',
      price: 999,
      discountPrice: 599,
      discountPercent: 40,
      rating: 4.7,
      reviewCount: 145,
      imageUrl: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=400&q=80',
      description: 'Handcrafted ceramic mugs, microwave and dishwasher safe.',
    ),
    Product(
      id: '16',
      name: 'Indoor Potted Plant (Snake Plant)',
      category: 'Home',
      price: 699,
      discountPrice: 399,
      discountPercent: 42,
      rating: 4.8,
      reviewCount: 410,
      imageUrl: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=400&q=80',
      description: 'Low-maintenance indoor air-purifying plant with an elegant white pot.',
    ),
  ];
}
